[workspace]
members = ["crates/*"]

resolver = "3"

[workspace.dependencies]
serde = { version = "1.0" }
serde_json = { version = "1.0" }
tokio = { version = "1.44" }
schemars08 = { version = "0.8", package = "schemars" }
schemars1 = { version = "1.0.0-alpha.17", package = "schemars" }
